language: python
python:
    - 2.7
    - 3.4
    - 3.5
    - 3.6
install:
    - pip install -U setuptools zc.buildout
    - buildout
before_script:
    - ./bin/flake8 bvc/
script:
    - ./bin/cover
after_success:
    - ./bin/coveralls
