language: python
python:
    - 2.7
    - 3.3
    - 3.4
install:
    - pip install -U setuptools zc.buildout
    - ./bin/buildout
before_script:
    - ./bin/flake8 --application-import-names bvc bvc/
script:
    - ./bin/cover
after_success:
    - ./bin/coveralls
