language: python
python:
    - 3.7
    - 3.8
install:
    - pip install -U setuptools zc.buildout
    - buildout
before_script:
    - ./bin/flake8 bvc/
script:
    - ./bin/cover
after_success:
    - ./bin/coveralls
