language: python
python:
    - "2.7"
install:
    - pip install -U setuptools
    - python bootstrap.py
    - ./bin/buildout
before_script:
    - ./bin/flake8 bvc
script:
    - ./bin/test
after_success:
    - ./bin/coveralls
